sonar.projectKey=azizlejmi12_to-do
sonar.organization=azizlejmi12
sonar.projectName=ProjetMERN DevOps
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/__tests__/**,**/coverage/**
sonar.sourceEncoding=UTF-8 
